import { ProviderType, ModelId, NodeId } from './workflow.types';

// ─── Memory Tier ──────────────────────────────────────────────────────────────

/**
 * Tiered storage levels inside .fluxion/memory/.
 * - GLOBAL:     global-context.md — Pinned rules, never pruned.
 * - SHORT_TERM: short-term/{nodeId}.md — Raw output of recent nodes. Pruned after workflow completes.
 * - LONG_TERM:  long-term/index.md — Summarised history across sessions.
 */
export enum MemoryTier {
  GLOBAL = 'GLOBAL',
  SHORT_TERM = 'SHORT_TERM',
  LONG_TERM = 'LONG_TERM',
}

// ─── Frontmatter Metadata ────────────────────────────────────────────────────

/**
 * Standard Frontmatter YAML block written at the top of every .md file
 * generated by Fluxion agents.
 *
 * schemaVersion allows future Fluxion releases to safely parse old .md files
 * without crashing — parse logic can branch on version number.
 */
export interface FrontmatterMetadata {
  /** Version of this Frontmatter schema. Increment only on breaking changes. */
  schemaVersion: '1.0';
  nodeId: NodeId;
  provider: ProviderType;
  model: ModelId;
  /**
   * - completed: Output is valid and safe to use as context for subsequent nodes.
   * - aborted:   Execution was cut short. Output is partial — subsequent nodes MUST NOT use this as context.
   */
  status: 'completed' | 'aborted';
  /** Unix ms timestamp when the agent finished writing this file. */
  timestamp: number;
  /** Human-readable model name used for this execution (e.g. 'gpt-5.5'). */
  modelName?: string;
}

// ─── Memory Records ──────────────────────────────────────────────────────────

/**
 * In-memory representation of a node's persisted output.
 * Mirrors the Frontmatter YAML + content of a short-term .md file.
 */
export interface NodeMemoryOutput {
  meta: FrontmatterMetadata;
  /** Raw markdown content (the body below the frontmatter block). */
  content: string;
}

export interface WorkspaceMemory {
  workspacePath: string;
  /** Raw content of global-context.md (the Pinned context). */
  globalContext: string;
}
